refresh_rate: 30 seconds
appenders:
  console:
    kind: console
  file:
    kind: rolling_file
    path: "log/mon.log"
    append: false
    encoder:
      pattern: "{d} - {m}{n}"
    # The policy which handles rotation of the log file. Required.
    policy:
      # Identifies which policy is to be used. If no kind is specified, it will
      # default to "compound".
      kind: compound

      # The remainder of the configuration is passed along to the policy's
      # deserializer, and will vary based on the kind of policy.
      trigger:
        kind: size
        limit: 10 mb

      roller:
        kind: delete
root:
  level: info
  appenders:
    - console
    - file